package com.smartims.insurancepractice.insurancenow.testscenario03;

public class Constants_03 {
    public static final String localHostUrl = "http://localhost:8080/innovation";
    public static final String username = "j_username";
    public static final String password = "j_password";
    public static final String newQuoteButton = "//*[@id=\"QuickAction_NewQuote_Holder\"]/span";
    public static final String newBusinessStateCode = "QuickAction_StateCd";
    public static final String newBusinessEffectiveDate = "QuickAction_EffectiveDt";

    public static final String newBusinessProgramType = "QuickAction_ProgramType";
    public static final String quickActionNewQuote = "QuickAction_NewQuote";
    public static final String continueButton = "Continue";
    public static final String newBusinessProducerCode = "ProviderNumber";
    public static final String newBusinessProducerLookup = "ProducerLookup";
    public static final String basicPolicyNolapse = "BasicPolicy.NoLapse";
    public static final String basicPolicyUninsuredMorethanThirtyDays = "BasicPolicy.UninsuredMoreThanThirtyDays";
    public static final String newBusinessEntityType = "Insured.EntityTypeCd";
    public static final String newBusinessInsuredFirstName = "InsuredName.GivenName";
    public static final String newBusinessInsuredMiddleName = "InsuredName.OtherGivenName";
    public static final String newBusinessInsuredLastName = "InsuredName.Surname";
    public static final String resetCommercialName = "ResetCommercialName";
    public static final String newBusinessInsuredPersonalBirthDate = "InsuredPersonal.BirthDt";

    public static final String newBusinessInsuredMailingAddress = "InsuredMailingAddr.Addr1";
    public static final String newBusinessInsuredMailingAddressCity = "InsuredMailingAddr.City";
    public static final String newBusinessInsuredMailingAddressPostalCode = "InsuredMailingAddr.PostalCode";
    public static final String newBusinessInsuredMailingAddressState = "InsuredMailingAddr.StateProvCd";
    public static final String newBusinessInsuredMailingAddressVerify = "InsuredMailingAddr.addrVerifyImg";
    public static final String newBusinessInsuredEmailAddress = "InsuredEmail.EmailAddr";
    public static final String newBusinessInsuredPersonalBestWayToContact = "InsuredPersonal.BestWayToContact";
    public static final String newBusinessInsuredPersonalBestTimeToContact = "InsuredPersonal.BestTimeToContact";
    public static final String nextPageBottom = "NextPage_Bottom";
    public static final String quoteCustomer = "QuoteCustomerClearingRef_2";
    public static final String newBusinessBodilyInjuryLimit = "Line.BILimit";
    public static final String newBusinessPropertyDamageLimit = "Line.PDLimit";
    public static final String newBusinessMedicalPaymentLimit = "Line.MedPayLimit";
    public static final String newBusinessPersonalInjuryProtectionLimit = "Line.PIPLimit";
    public static final String newBusinessUninsured_UnderInsuredMotoristBodilyInjury = "Line.UMUILimit";
    public static final String newBusinessUninsured_UnderInsuredMotoristPropertyDamage = "Line.UMUIPDLimit";
    public static final String newBusinessHomeOwnersDiscount = "Line.HomeownersDiscountInd";
    public static final String newBusinessAddDriver = "AddDriver";
    public static final String newBusinessDriver1FirstName = "NameInfo.GivenName";
    public static final String newBusinessDriver1Surname = "NameInfo.Surname";
    public static final String newBusinessDriver1RelationshipToInsured = "DriverInfo.RelationshipToInsuredCd";
    public static final String newBusinessDriver1Status = "DriverInfo.DriverStatusCd";
    public static final String newBusinessDriver1BirthDate = "PersonInfo.BirthDt";
    public static final String newBusinessDriver1Gender = "PersonInfo.GenderCd";
    public static final String newBusinessDriver1MaritalStatus = "PersonInfo.MaritalStatusCd";
    public static final String newBusinessDriver1LicenseDate = "DriverInfo.LicenseDt";
    public static final String newBusinessDriver1LicenseNumber = "DriverInfo.LicenseNumber";
    public static final String newBusinessDriver1LicenseStatus = "DriverInfo.LicenseStatus";
    public static final String newBusinessDriver1SR22 = "DriverInfo.SR22";
    // public static final String = "DriverInfo.ScholasticDiscountInd";
    public static final String newBusinessDriver1OccupationStatus = "PersonInfo.OccupationStatus";
    public static final String navigateAddRiskPrivatePassengerAuto = "Navigate_AddRisk_PrivatePassengerAuto";
    public static final String newBusinessVehicle1VIN = "Vehicle.VehIdentificationNumber";
    public static final String validateVin = "ValidateVIN";
    public static final String newBusinessVehicle1Use = "Vehicle.VehUseCd";
    public static final String newBusinessVehicle1PurchasedOrLeased = "Vehicle.LeasedVehInd";
    public static final String newBusinessVehicle1OtherThanCollisionDeductible = "Vehicle.OtherThanCollisionDed";
    public static final String newBusinessVehicle1CollisionDeductible = "Vehicle.CollisionDed";
    public static final String newBusinessVehicle1RentalReimbursement = "Vehicle.RentalReimbursementLimit";
    public static final String newBusinessVehicle1TowingAndLabor = "Vehicle.TowingLaborLimit";
    public static final String newBusinessVehicle1SpecialEquipment = "Vehicle.SpecialEquipmentLimit";
    public static final String newBusinessPayPlans = "BasicPolicy.PayPlanCd_1";
    public static final String bindButton = "Bind";
    public static final String newBusinessWizardUnderwriting = "Wizard_Underwriting";
    public static final String questionProperLicense = "Question_ProperLicense";
    public static final String questionPossibleDriver = "Question_PossibleDriver";
    public static final String questionDriverConviction = "Question_DriverConviction";
    public static final String questionHouseholdResident = "Question_HouseholdResident";
    public static final String questionExcludedSpouse = "Question_ExcludedSpouse";
    public static final String questionBusinessVehicle = "Question_BusinessVehicle";
    public static final String questionExistingDamage = "Question_ExistingDamage";
    public static final String questionDifferentAddress = "Question_DifferentAddress";
    public static final String questionSpecialEquipment = "Question_SpecialEquipment";
    public static final String questionOtherVehicle = "Question_OtherVehicle";
    public static final String questionTitledVehicle = "Question_TitledVehicle";
    public static final String questionDriverViolation = "Question_DriverViolation";
    public static final String questionDriverCondition = "Question_DriverCondition";
    public static final String questionVehicleModification = "Question_VehicleModification";
    public static final String questionLiveryVehicle = "Question_LiveryVehicle";
    public static final String closeOut = "//*[@id=\"Closeout\"]/span";
    public static final String paymentTypeCode = "TransactionInfo.PaymentTypeCd";
    public static final String process = "//*[@id=\"Process\"]/span";
// public static final String = "";
// public static final String = "";
// public static final String = "";
// public static final String = "";
// public static final String = "";

    public static final String policySearchTab = "//*[@id=\"AdvancedSearchPolicy\"]";
    public static final String policyNumberTextField = "//*[@id=\"PolicyNumber\"]";
    public static final String searchButton = "//*[@id=\"SearchPolicy\"]";
    public static final String startTransactionButton = "//*[@id=\"Transaction\"]/span";
    public static final String startNewTransaction = "//*[@id=\"TransactionCd\"]";
    public static final String selectButton = "//*[@id=\"Select\"]";
    public static final String endorsementEffDate = "//*[@id=\"TransactionEffectiveDt\"]";
    public static final String startButton = "//*[@id=\"Start\"]";
    public static final String entityType = "//*[@id=\"Insured.EntityTypeCd\"]";
    public static final String firstname = "//*[@id=\"InsuredName.GivenName\"]";
    public static final String middlename = "//*[@id=\"InsuredName.OtherGivenName\"]";
    public static final String lastname = "//*[@id=\"InsuredName.Surname\"]";
    public static final String cancellationNoticeDate = "//*[@id=\"NoticeDt\"]";
    public static final String cancellationType = "//*[@id=\"CancelRequestedByCd\"]";
    public static final String additionalNoticeText = "//*[@id=\"TransactionLongDescription\"]";
    public static final String processButton = "//*[@id=\"Process\"]/span";




    public static final String billingTabId = "Tab_Billing";
    public static final String adminTabId = "Menu_Admin";
    public static final String changeDateId = "Menu_Admin_ChangeDate";
 public static final String  makePayment= "/html/body/main/form/div[1]/aside[2]/div[2]/div[1]/a[3]/span";
 public static final String pay = "QuickAction_SubmitPayment";
 public static final String newCreditCardId= "PaymentTypeCd_3";
 public static final String  newPremiumAmount= "PremiumReceiptAmt";
 public static final String totalAmount= "ReceiptAmt";
// public static final String = "";
// public static final String = "";
// public static final String = "";
}
